<template>
    <table width="100%" bordercolor="#6b8fa3" class="FormTable" v-if="dns">
        <thead>
            <tr>
                <td colspan="2">DNS
                    <hint>
                        The DNS module built into Xray has two main purposes:
                        <ul>
                            <li>During the routing phase, it resolves domain names to IP addresses and performs traffic
                                splitting based on the results of domain name resolution and the value of domainStrategy
                                in the routing configuration module. The built-in DNS server is only used for DNS
                                queries when either of the following values is set:
                                <ul>
                                    <li>**IPIfNonMatch**: When a domain name is requested, it first tries to match it
                                        against the domain entries in the routing configuration. If no match is found,
                                        the built-in DNS server is used to perform a DNS query for the domain name, and
                                        the returned IP address is used to perform IP routing matching again.</li>
                                    <li>**IPOnDemand**: When a domain name is matched against any IP-based rule, it is
                                        immediately resolved to an IP address for matching.</li>
                                </ul>
                            </li>
                            <li>It resolves the target address for connection.</li>
                            <li>In the freedom outbound setting, if **domainStrategy** is set to **UseIP**, requests
                                made
                                through the outbound proxy will first resolve the domain name to an IP address using the
                                built-in server before making the connection.</li>
                            <li>In the sockopt setting, if **domainStrategy** is set to **UseIP**, system connections
                                initiated
                                through the outbound proxy will first be resolved to an IP address using the built-in
                                server before making the connection.</li>
                        </ul>

                    </hint>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Tag
                    <hint>
                        Traffic generated by built-in **DNS**, except for localhost, fakedns, **TCPL**, **DOHL**, and
                        **DOQL**
                        modes, can be matched with `inboundTag` in routing using this identifier.
                    </hint>
                </th>
                <td>
                    <input type="text" class="input_20_table" v-model="dns.tag" />
                    <span class="hint-color"></span>
                </td>
            </tr>
            <tr v-if="dns.hosts">
                <th>Hosts
                    <hint>
                        A list of static `IP addresses`, with values consisting of a series of domains and addresses.
                        The
                        address can be an IP or a domain name.
                        When resolving a domain name, if the domain name matches an item in this list:
                        <ul>
                            <li>If the address of the item is an IP, the resolution result will be that IP.</li>
                            <li>If the address of the item is a domain name, this domain name will be used for IP
                                resolution instead of the original domain name.</li>
                            <li>If multiple IPs and domain names are set in the address, only the first domain name will
                                be returned, and the rest of the IPs and domain names will be ignored.</li>

                        </ul>
                    </hint>

                </th>
                <td>
                    {{ Object.getOwnPropertyNames(dns.hosts).length }} item(s)
                    <input class="button_gen button_gen_small" type="button" value="Manage"
                        @click.prevent="manage_hosts()" />
                    <span class="hint-color"></span>
                    <dns-hosts-modal ref="modalHosts" v-model:hosts="dns.hosts"></dns-hosts-modal>
                </td>
            </tr>
            <tr v-if="dns.servers">
                <th>Servers
                    <hint>
                        A list of DNS servers. The address can be an IP or a domain name.
                        When resolving a domain name, the DNS server will be used for resolution.
                    </hint>
                </th>
                <td>
                    {{ dns.servers.length }} item(s)
                    <input class="button_gen button_gen_small" type="button" value="Manage"
                        @click.prevent="manage_servers()" />
                    <span class="hint-color"></span>
                    <dns-servers-modal ref="modalServers" v-model:servers="dns.servers"></dns-servers-modal>
                </td>
            </tr>
            <tr v-if="engine.mode == 'client'">
                <th>Client ip
                    <hint>
                        Used to notify the server of the specified IP location during `DNS` queries. Cannot be a private
                        address.
                    </hint>
                </th>
                <td>
                    <input type="text" maxlength="15" class="input_20_table" v-model="dns.clientIp"
                        onkeypress="return validator.isIPAddr(this, event);" autocomplete="off" autocorrect="off"
                        autocapitalize="off" />
                    <span class="hint-color"></span>
                </td>
            </tr>
            <tr>
                <th>Query strategy
                    <hint>
                        `UseIPv4` only queries A records; `UseIPv6` only queries `AAAA` records. The default value is
                        `UseIP`,
                        which queries both `A` and `AAAA` records.
                    </hint>

                </th>
                <td>
                    <select class="input_option" v-model="dns.queryStrategy">
                        <option v-for="(opt, index) in strategyOptions" :key="index" :value="opt">
                            {{ opt }}
                        </option>
                    </select>
                    <span class="hint-color">default: UseIP</span>
                </td>
            </tr>
            <tr>
                <th>Disable cache
                    <hint>
                        `true` disables DNS caching, default is `false` which means caching is not disabled.
                    </hint>
                </th>
                <td>
                    <input type="checkbox" v-model="dns.disableCache" />
                    <span class="hint-color">default: false</span>
                </td>
            </tr>
            <tr>
                <th>Disable fallback
                    <hint>
                        `true` disables fallback DNS queries, default is `false` which means fallback queries are not
                        disabled.
                    </hint>
                </th>
                <td>
                    <input type="checkbox" v-model="dns.disableFallback" />
                    <span class="hint-color">default: false</span>
                </td>
            </tr>
            <tr>
                <th>Disable fallbackI if match
                    <hint>
                        `true` disables fallback DNS queries when the matching domain list of the DNS server is hit,
                        default is `false` which means fallback queries are not disabled.
                    </hint>
                </th>
                <td>
                    <input type="checkbox" v-model="dns.disableFallbackIfMatch" />
                    <span class="hint-color">default: false</span>
                </td>
            </tr>
        </tbody>
    </table>
</template>

<script lang="ts">
import { defineComponent, ref, watch } from "vue";
import engine from "../modules/Engine";
import { XrayDnsObject } from "../modules/CommonObjects";
import xrayConfig from "../modules/XrayConfig";
import DnsHostsModal from "./modals/DnsHostsModal.vue";
import DnsServersModal from "./modals/DnsServersModal.vue";
import Hint from "./Hint.vue";

export default defineComponent({
    name: "Dns",
    components: {
        Hint,
        DnsHostsModal,
        DnsServersModal
    },

    methods: {
        manage_hosts() {
            this.modalHosts.show();
        },
        manage_servers() {
            this.modalServers.show();
        }
    },
    setup() {
        const config = ref(engine.xrayConfig);
        const dns = ref<XrayDnsObject>(config.value.dns ?? new XrayDnsObject());
        const modalHosts = ref();
        const modalServers = ref();

        watch(
            () => config.value.dns,
            (newObj) => {
                dns.value = newObj ?? new XrayDnsObject();
                if (!newObj) {
                    xrayConfig.dns = dns.value;
                }
            },
            { immediate: true }
        );

        return {
            engine,
            dns,
            modalHosts,
            modalServers,
            strategyOptions: XrayDnsObject.strategyOptions
        }
    },
});
</script>