name: Build and Upload Artifacts

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Build version"
        required: true
        default: "0.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install XRAYUI dependencies
        run: npm install

      - name: Build XRAYUI
        run: npm run build

      - name: Install WebApp dependencies
        run: |
          cd tools/webapp
          npm install

      - name: Build WebApp
        run: |
          cd tools/webapp
          npm run build

      - name: Update XRAYUI Version
        env:
          XRAYUI_VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Updating XRAYUI_VERSION to $XRAYUI_VERSION in /dist/xrayui"
          sed -i "s/^XRAYUI_VERSION=.*/XRAYUI_VERSION=\"$XRAYUI_VERSION\"/" dist/xrayui

      - name: Archive XRAYUI dist
        run: tar --transform 's|^|xrayui/|' -czf asuswrt-merlin-xrayui.tar.gz -C dist .

      - name: Archive WebApp dist
        run: |
          cd tools/webapp
          tar -czf ./../../xrayui-webapp.tar.gz -C ./dist .

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: tools/xraydatbuilder/src/go.mod

      - name: Build xraydatbuilder
        run: |
          cd tools/xraydatbuilder/src || exit 1
          chmod +x ./build.sh
          ./build.sh
          tar -czf ./../../../xrayui-datbuilder.tar.gz -C ../dist .

      - name: Upload XRAYUI Artifact
        uses: actions/upload-artifact@v3
        with:
          name: asuswrt-merlin-xrayui
          path: asuswrt-merlin-xrayui.tar.gz

      - name: Upload WebApp Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xrayui-webapp
          path: xrayui-webapp.tar.gz

      - name: Upload xrayui-datbuilder Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xrayui-datbuilder
          path: xrayui-datbuilder.tar.gz
